const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {build}=require('../scripts/build-text-overlays');
const {renderPanel,overlaySvg}=require('../scripts/render-panel-overlays');
function fixture(){const r=fs.mkdtempSync(path.join(os.tmpdir(),'cle3-canonical-'));for(const p of ['script','panels'])fs.mkdirSync(path.join(r,'episodes/EP999',p),{recursive:true});const write=(p,d)=>fs.writeFileSync(path.join(r,'episodes/EP999',p),JSON.stringify(d));write('panels/panels.json',{panels:[{panel_id:'p1-1',page_number:1,description:'family dinner',image_path:'source.png',generation_status:'generated'}]});fs.writeFileSync(path.join(r,'episodes/EP999/script/script.md'),'| 1-1 | laboratory | note | WRONG TEXT | camera | color |');const canonical={episode_id:'EP999',version:1,panels:[{panel_id:'p1-1',page_number:1,description:'family dinner',text:[]}]};write('script/panel-script.json',canonical);return {r,write,canonical};}
test('canonical silence replaces unrelated legacy text and remains draft pending visual QA',()=>{const {r,write}=fixture();write('panels/text-overlays.json',{panels:[{panel_id:'p1-1',status:'rendered',overlays:[{text:'WRONG'}]}]});const result=build(r,'EP999',true);assert.deepEqual(result.panels[0].overlays,[]);assert.equal(result.panels[0].status,'draft');});
test('same ID with changed scene is rejected before output mutation',()=>{const {r,write,canonical}=fixture();canonical.panels[0].description='laboratory';write('script/panel-script.json',canonical);assert.throws(()=>build(r,'EP999',true),/scene mismatch/);assert.equal(fs.existsSync(path.join(r,'episodes/EP999/panels/text-overlays.json')),false);});
test('changed canonical dialogue invalidates previous visual review',()=>{const {r,write,canonical}=fixture();const first=build(r,'EP999',true);first.panels[0].status='approved';write('panels/text-overlays.json',first);canonical.panels[0].text=[{kind:'dialogue',text:'새 대사'}];write('script/panel-script.json',canonical);assert.equal(build(r,'EP999',true).panels[0].status,'draft');});
test('held panels are not rendered and long dialogue is never silently discarded',()=>{assert.equal(renderPanel('/missing',{status:'needs_review'}),false);const svg=overlaySvg({kind:'dialogue',text:'하나 둘 셋 넷 다섯 여섯 일곱 여덟 아홉 열 마지막',box:{x:0,y:0,w:.15,h:1}},1000,1000);assert.match(svg,/마지막/);});
test('replacing artwork invalidates visual review while an unchanged source retains it',()=>{const {r,write}=fixture();fs.writeFileSync(path.join(r,'source.png'),'first artwork');const first=build(r,'EP999',true);first.panels[0].status='approved';write('panels/text-overlays.json',first);assert.equal(build(r,'EP999',true).panels[0].status,'approved');fs.writeFileSync(path.join(r,'source.png'),'corrected artwork');assert.equal(build(r,'EP999',true).panels[0].status,'draft');});
